name: lint

on:
  pull_request:
    types: [opened, synchronize]
  push:

jobs:
  lint:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"
          channel: 'stable'
      - name: flutter pub get
        run: flutter pub get
      - name: flutter analyze
        continue-on-error: true
        run: flutter analyze > flutter_analyze_report.txt
      - name: Run Danger
        uses: danger/danger-js@9.1.8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
